name: read secret

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  check-read-secret:

    runs-on: ubuntu-latest

    steps:
      - name: check_secret_step
        env: MY_FIRST_SECRET_NAME_ENV = ${{secrets.MY_FIRST_SECRET}}
        run: |
             echo "Il mio primo secret $MY_FIRST_SECRET_NAME"